---
title: "The Smiths"
author: "Andres Gonzalez"
date: "2023-03-27"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(spotifyr)
library(gt)
library(gtExtras)
library(showtext)
library(ggtext)
library(paletteer)
library(ggchicklet)
library(ggrepel)
```


```{r}
# Call the 'get_artist_audio_features()' function with the argument 'the smiths'
# This function should query the Spotify API for audio features of songs by the artist 'The Smiths'
# Store the retrieved audio features in the variable 'smiths'
smiths <- get_artist_audio_features('the smiths')
```

```{r}
font_add_google(family = "lato", "Lato")
font_add(family = "bodoni", "/Users/andres/Library/Fonts/BodoniFLF-Bold.ttf")
font_add("Gotham", "/Users/andres/Library/Fonts/GothamMedium.ttf")

showtext_opts(dpi = 300)
showtext_auto()

smiths_filtered <- smiths %>%
  filter(album_name %in% c("The Smiths","Meat Is Murder", "The Queen Is Dead", "Strangeways, Here We Come")) %>%
  group_by(album_name) %>%
  count(key_mode)

smiths_filtered %>%
  ggplot(aes(x = key_mode, y = n)) +
  geom_chicklet(aes(fill = album_name), width = 0.75) +
  geom_text(aes(label = n),
            size = 3,
            color = "white",
            position = position_stack(vjust = 0.5)) +
  labs(title = "Key Mode Distribution of <span style = 'color:#06A6DA'>The Smiths</span> Across Albums") +
  scale_y_continuous(breaks = seq(0,10, by = 2)) +
  scale_fill_manual(values = c("#AD9CB7","#013706", "#B83868", "#AE9946"),
                    breaks = c("The Smiths","Meat Is Murder", "The Queen Is Dead", "Strangeways, Here We Come")) +
  theme_minimal() +
  theme(
    text = element_text(family = "lato"),
    plot.title = element_markdown(size = 20, face = "bold", hjust = 0.5),
    plot.title.position = "plot",
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.title = element_blank(),
    legend.position = "bottom",
    legend.title = element_blank()
  )

```

```{r}
vars_audio = c('danceability',
               'energy',
               'loudness',
               'acousticness',
               'instrumentalness')

smiths_filtered <- smiths %>%
  filter(album_name %in% c("The Smiths","Meat Is Murder", "The Queen Is Dead", "Strangeways, Here We Come")) %>%
  select(
    artist_id,
    artist_name,
    album_id,
    album_name,
    album_release_date,
    album_images,
    track_name,
    duration_ms,
    all_of(vars_audio)) %>%
  arrange(desc(album_release_date))
```

```{r}
smiths_filtered %>%
  glimpse()
```

```{r}
table <- smiths_filtered %>%
  head() %>%
  select(artist_name, album_name, track_name, all_of(vars_audio)) %>%
  
  # En este paso se transforma el df en un objeto gt:
  gt()

table
```

```{r}
table %>%
  fmt_number(columns = where(is.numeric), decimals = 2)
```

```{r}
df_albums <- smiths_filtered %>%
  
  group_by(album_images,
           artist_name,
           album_id,
           album_name,
           album_release_date) %>%
  
  summarise(# Duraci칩n del 치lbum: suma de duraci칩n de cada canci칩n
    duration_mins = sum(duration_ms / (1000 * 60)),
    
    # Lista de cada variable de audio
    across(all_of(vars_audio), ~ list(.x)),) %>%
  
  ungroup()
```

```{r}
table_albums <- df_albums %>%
  select(-album_images) %>%
  gt() 

table_albums
```

```{r}
get_imagen = function(album_images) {
  album_images %>%
    data.frame() %>%
    filter(height == 64) %>%
    pull(url) %>%
    as.character()
}
```

```{r}
df_albums <- df_albums %>%
  mutate(album_images = map(album_images, ~ get_imagen(album_images = .x))) %>%
  distinct()
```

```{r}
table_albums <- df_albums %>%  select(-album_id) %>%
  
  gt() %>%
  
  tab_header(title = md("<span style= 'font-size:24pt; font-family:bodoni; color:#EE2E34;'>THE SMITHS</span> in Spotify"),
             subtitle = "All Studio Albums") %>%
  
  text_transform(
    locations = cells_body(columns = c(album_images)),
    fn = function(album_images) {
      lapply(album_images, web_image, height = 50)
    }
  ) 

table_albums
```

```{r}
table_albums <- table_albums %>%
  
  gt_merge_stack(col1 = album_name,
                 col2 = artist_name) 

table_albums
```

```{r}
table_albums %>%
  cols_hide(all_of(vars_audio))
```

```{r}
library(svglite)
color_spotify = "#1DB954"

table_albums <- table_albums %>%
  gt_color_box(
    columns = duration_mins,
    palette = c('white', color_spotify),
    domain = c(0, round(max(df_albums$duration_mins)) + 1)) %>%
  
  gt_plt_dist(
    column = danceability,
    type = "density",
    line_color = "black",
    fill_color = color_spotify
  ) %>%
  
  gt_plt_dist(
    column = energy,
    type = "density",
    line_color = "black",
    fill_color = color_spotify
  ) %>%
  
  gt_plt_dist(
    column = loudness,
    type = "density",
    line_color = "black",
    fill_color = color_spotify
  ) %>%
  
  gt_plt_dist(
    column = acousticness,
    type = "boxplot",
    line_color = "black",
    fill_color = color_spotify
  )
```

```{r}
table_albums %>%
  cols_hide('instrumentalness')
```

```{r}
table_albums %>%
  gt_plt_dist(
    column = instrumentalness,
    type = "boxplot",
    line_color = "black",
    fill_color = color_spotify
  ) 
```

```{r}
gen_outliers_plots <- function(.df,
                               .variable,
                               .font_size = 4,
                               .lwd = 3) {
  temp <- .df %>%
    select(all_of(c('track_name', .variable))) %>%
    pivot_longer(cols = -track_name)
  
  track <- temp %>%
    slice(which.max(value)) %>%
    pull(track_name)
  
  temp %>%
    mutate(is_outlier = ifelse(track_name == track, track_name, NA)) %>%
    
    ggplot(aes(y = value, x = name)) +
    geom_boxplot(
      fill = color_spotify,
      width = 0.2,
      lwd = .lwd,
      outlier.size = 5
    ) +
    geom_text_repel(
      aes(label = is_outlier),
      na.rm = TRUE,
      nudge_x = 0.4,
      size = .font_size
    ) +
    coord_flip() +
    theme_void()
}
```


```{r}
gen_outliers_plots(
  .df = smiths_filtered %>% filter(album_name == 'Strangeways, Here We Come'),
  .variable = 'instrumentalness',
  .font_size = 10,
  .lwd = 0.5
)
```

```{r}
df_albums <- df_albums %>%
  mutate(instrumentalness = map(
    album_id,
    ~ gen_outliers_plots(.df = smiths_filtered %>% filter(album_id == .x),
                         .variable = 'instrumentalness')
  ))
```

```{r}
table_albums <- table_albums %>%
  
  text_transform(
    locations = cells_body(columns = instrumentalness),
    fn = function(x) {
      map(
        df_albums$instrumentalness,
        gt::ggplot_image,
        height = px(60),
        aspect_ratio = 2
      )
    }
  ) 

table_albums
```

```{r}
table_albums <- table_albums %>%
  tab_spanner(label = "Audio Features",
              columns = danceability:instrumentalness) %>%
  cols_label(
    album_images = "",
    album_name = "",
    album_release_date = "Release Date",
    duration_mins = "Duration",
    danceability = "Danceability",
    energy = "Energy",
    loudness = "Loudness",
    acousticness = "Acousticness",
    instrumentalness = "Instrumentalness"
  ) 
                  
```

```{r}
my_theme <- function(gt_object, ...) {
  gt_object %>%
    tab_options(
      column_labels.background.color = "#2C3525",
      footnotes.background.color = "#2C3525",
      source_notes.background.color = "#2C3525",
      heading.background.color = "#2C3525",
      heading.align = "left",
      ...
    ) %>%
    tab_style(style = cell_text(size = px(22)),
              locations = cells_title("title"))
}
```

```{r}
table_albums1 <- table_albums %>%
  my_theme() %>%
  tab_footnote(
    locations = cells_column_labels("duration_mins"),
    footnote = "Duration is the total length of all tracks in each album, represented in minutes and may be approximate."
  ) %>%
  tab_source_note(md("**Table**: @AndresAnalytics | **Data**: spotifyr <br> **Inspiration**: @me_andre "))

table_albums1
```


